
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds/status
  verbs:
  - get
  - patch
  - update
