# permissions for end users to edit samplecrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samplecrd-editor-role
rules:
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds/status
  verbs:
  - get
