# permissions for end users to view samplecrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samplecrd-viewer-role
rules:
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.local.domin
  resources:
  - samplecrds/status
  verbs:
  - get
